import { Building2, GraduationCap, Landmark, UserRound } from 'lucide-react'
import type { DirectoryEntry } from './studentDirectory.types'

export const directoryEntries: DirectoryEntry[] = [
  {
    id: 'student-affairs',
    kind: 'office',
    name: 'Office of Student Affairs',
    description: 'Handles student life concerns, organization support, conduct, and routed cases.',
    contact: 'osa@cares.edu.ph',
    location: 'Student Center, 2F',
    hours: 'Monday to Friday, 8:00 AM - 5:00 PM',
    concernsHandled: 18,
    concernsResolved: 14,
    responsiveness: 78,
    mainConcerns: ['Student conduct', 'Organization activities', 'Campus experience'],
    icon: Landmark,
  },
  {
    id: 'registrar',
    kind: 'office',
    name: 'Registrar',
    description: 'Supports enrollment, records, document requests, and clearance verification.',
    contact: 'registrar@cares.edu.ph',
    location: 'Administration Building',
    hours: 'Monday to Friday, 8:00 AM - 4:30 PM',
    concernsHandled: 12,
    concernsResolved: 9,
    responsiveness: 75,
    mainConcerns: ['Student records', 'Enrollment', 'Document requests'],
    icon: Building2,
  },
  {
    id: 'guidance',
    kind: 'office',
    name: 'Guidance Office',
    description: 'Provides counseling, wellness referrals, and confidential student support.',
    contact: 'guidance@cares.edu.ph',
    location: 'Arrupe Hall',
    hours: 'Monday to Friday, 9:00 AM - 5:00 PM',
    concernsHandled: 10,
    concernsResolved: 8,
    responsiveness: 80,
    mainConcerns: ['Counseling', 'Wellness support', 'Referral assistance'],
    icon: Landmark,
  },
  {
    id: 'computer-studies',
    kind: 'department',
    name: 'Computer Studies',
    description: 'Coordinates academic concerns, faculty consultation, and program support.',
    contact: 'csdept@cares.edu.ph',
    location: 'College Building, 3F',
    hours: 'Monday to Friday, 8:00 AM - 5:00 PM',
    concernsHandled: 16,
    concernsResolved: 12,
    responsiveness: 82,
    mainConcerns: ['Academic consultation', 'Capstone support', 'Lab access'],
    relatedOffice: 'College Dean',
    facultyLead: 'Prof. Adrian Lee',
    icon: GraduationCap,
  },
  {
    id: 'business-admin',
    kind: 'department',
    name: 'Business Administration',
    description: 'Receives course, practicum, and faculty-related department concerns.',
    contact: 'businessdept@cares.edu.ph',
    location: 'College Building, 2F',
    hours: 'Monday to Friday, 8:30 AM - 5:00 PM',
    concernsHandled: 9,
    concernsResolved: 7,
    responsiveness: 77,
    mainConcerns: ['Course advising', 'Practicum', 'Faculty consultation'],
    relatedOffice: 'College Dean',
    facultyLead: 'Dr. Maria Santos',
    icon: GraduationCap,
  },
  {
    id: 'maria-santos',
    kind: 'faculty',
    name: 'Dr. Maria Santos',
    description: 'Faculty adviser for academic consultation and department escalation support.',
    contact: 'maria.santos@cares.edu.ph',
    location: 'Faculty Room A',
    hours: 'Tuesday and Thursday, 1:00 PM - 4:00 PM',
    concernsHandled: 7,
    concernsResolved: 6,
    responsiveness: 86,
    mainConcerns: ['Academic consultation', 'Advising', 'Course planning'],
    relatedOffice: 'Business Administration',
    icon: UserRound,
  },
  {
    id: 'adrian-lee',
    kind: 'faculty',
    name: 'Prof. Adrian Lee',
    description: 'Supports capstone, programming courses, and faculty consultation appointments.',
    contact: 'adrian.lee@cares.edu.ph',
    location: 'Computer Studies Faculty Room',
    hours: 'Monday and Wednesday, 10:00 AM - 3:00 PM',
    concernsHandled: 11,
    concernsResolved: 9,
    responsiveness: 84,
    mainConcerns: ['Capstone', 'Programming courses', 'Lab schedules'],
    relatedOffice: 'Computer Studies',
    icon: UserRound,
  },
]
