export { AdminDashboardPage } from './AdminDashboardPage'
export { AdminDepartmentsPage } from './AdminDepartmentsPage'
export { AdminFacultyPage } from './AdminFacultyPage'
export { AdminOfficesPage } from './AdminOfficesPage'
export { AdminStudentsPage } from './AdminStudentsPage'
